[versions]
agp = "8.13.0"
kotlin = "2.2.0"
junit = "4.13.2"
mavenPublish = "0.37.0"
klaudeAuth = "0.2.0"

[libraries]
klaude-auth = { group = "io.github.tom-spalding", name = "klaude-auth", version.ref = "klaudeAuth" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
